# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

domain: ivonr7.github.io
title:  Isaac von Riedemann 
email: ivonriedemann@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  This webpage is a personal portfolio of projects built by Isaac von Riedemann.  These
  projects include image processing, computational photography and compututational art.
  it's based on the minimal-mistakes theme built for jekyll and hosted on github pages
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://ivonr7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "ivonr7/portfolio"
github_username: ivonr7 

# Build settings
remote_theme: mmistakes/minimal-mistakes 
minimal_mistakes_skin: dirt
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      author_profile: false 


collections:
  projects:
    output: true
    permalink: /:collection/:path/


author:
  name: "Isaac von Riedemann"
  avatar: "/assets/images/me_at_dinner.jpeg"
  bio: "Computer Science Student at Simon Fraser University (SFU), focusing on computational vision, photography and optics"
  location: "Vancouver, BC"
  email: "ivonriedemann@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ivonr7"
    - label: "Resume"
      icon: "fas fa-bookmark"
      url: "/portfolio/assets/ivonr7_resume.pdf"
    - label: "LinkedIn"
      icon: "fa fa-linkedin"
      url: "https://www.linkedin.com/in/isaac-von-riedemann-483318223/"

